# Generated by Django 4.2 on 2023-04-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(verbose_name='date submitted')),
                ('done', models.BooleanField()),
            ],
        ),
    ]
