# Generated by Django 5.0.3 on 2024-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceCRM', '0002_insert_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insert',
            name='plateno',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
